### PR TITLE
Feature Request: reset with arguments

### PR DESCRIPTION
**Pull request by strin**
In envs like world-of-bits, we might want slightly different config for different episode, because an episode can condition on things like queries. For example, if we'd like to evaluate the agent's performance on a set of queries:

1. book flight from SFO to BOS
2. book flight from PEK to SFO
3. book flight from JFK to PIT

The client would need to set different queries for different episodes during evaluation, while being in the same env. 

This PR (still need to be cleaned up) creates a function `_episode_configure` for `VNCEnv`. So client can do 

```
env._episode_configure(query='hello, world')
env.reset()
```

### CODE REVIEW

**Comment by gdb** [comment]
Hm, I think this can be done in-band using special actions — that is, shouldn't need to create any new first-class methods for it. Did you run into trouble with that approach?

**Comment by strin** [comment]
you are right that probably not all universe envs need this feature. i'll keep this as a branch for now just for research purposes.

**Comment by strin** [comment]
@nottombrown @gdb here's a new proposal for this feature - reset with arguments:
```
env.reset(**kwargs)
```
Currently, we already have `env.reset(seed=...)`. This assumes the configuration of environments is drawn from a random distribution, and seed determines an instantiation. Sometimes, we want finer control of the initial state. A wide variety of environments will benefit from reset with args. For example, in WoB, we can have
```
env.reset(query='book a flight from SFO to BOS')
```
What do you guys think?

**Comment by gdb** [comment]
cc/ @joschu

**Comment by joschu** [comment]
I think the solution is to modify the core gym env so that you define `step` and `reset` rather than `_step` and `_reset` -- we're just forwarding these calls through anyway. That'll give people more flexibility to make misc small changes to the API.
@gdb what do you think?

**Comment by gdb** [comment]
+1 to switching to step/reset — we can do this in a backwards compatible way without issue.

**Comment by strin** [comment]
Great idea. Shall I go ahead and make some changes?

**Comment by gdb** [comment]
Yep, go ahead.

**Comment by strin** [comment]
Moving discussion to https://github.com/openai/universe/pull/164

**Pull request closed without merging**
