### PR TITLE
Move SafeActionSpace to wrappers.experimental module

### LINKED ISSUE #55: Support getting only game frames as observations
Would it be possible to support (through a wrapper or somesuch) to get only the game frame (for any environment & game)?
In other words, remove the browser and everything for the flash games.

### PR DESCRIPTION
**Pull request by nottombrown**
Some tweaks on top of #59 in order to preserve backwards compat

- [x] Create a new experimental package
- [x] Adds `CropObservations` wrapper
- [x] Move wrappers.SafeActionSpace to wrappers.experimental.SafeActionSpace
- [x] Maintains backwards compat with a deprecation warning.

Fixes #55

### CODE REVIEW

**Comment by nottombrown** [comment]
Was this the desired outcome @tlbtlbtlb / @gdb / @jderehag ?

**Comment by jderehag** [comment]
Hi, sorry for the tardiness on PR #59, have been travelling for the holidays so was unable to fix your comments.

Regarding this PR - LGTM, although I personally would be a bit hesitant about it. 

Adding a deprecation warning without explicitly breaking something *usually* leads to a lot of code lying around that nobody ever gets the time or inclination to remove. Since @gdb ack:ed breaking backwards compatibility I would personally rather have gone down that road, but in the end, its minor issues and you guys probably know better than me the tendencies in this particular community.

**Comment by jderehag** [comment]
Also, I would perhaps consider moving #63 - Add support for grayscale to the experimental package due to the discussion in #55 
As well as make #63 more generic (i.e make it into a wrapper) so that it optionally can be applied to any environment and not just the vnc environment.
(Adding as comment here due to that #63 was already delivered prior to this commit.)

**Comment by nottombrown** [comment]
I'd rather not break backwards compatibility without warning. I've added the deprecation, and will remove the old syntax four weeks from today.

**Pull request merged**
